### ISSUE TITLE
Relax nimble_parsec requirements to be `~> 0.2.2 or ~> 0.4` or similar

### ISSUE THREAD

**Issue by kipcole9** [tmbb/makeup_elixir#5]
According to mix hex.outdated nimble_parsec on Elixir 1.7.3 and OTP 20 I see:

```elixir
Source         Requirement       
mix.exs        ~> 0.2 or ~> 0.4  
makeup         ~> 0.2.2          
makeup_elixir  ~> 0.2.2 
```

Which means I can't use a version later than that in my project and mix hex.update nimble_parsec won 't allow the update.

**Comment by tmbb** [comment]
Thanks for the issue submission. Currently, publishing new Makeup versions is non-trivial because of this: https://github.com/elixir-lang/ex_doc/issues/894

Let me find out what the best option forward is, and I'll publish a new version relaxing the dependency.

**Comment by tmbb** [comment]
I've found a number of bugs which I'll have to address first. Thanks for your patience :)

**Comment by tmbb** [comment]
Fixed in the newest version (`{:makeup_elixir, "0.8.1"}`)

**Comment by kipcole9** [comment]
Thanks much - working well for me!
